version: "3.7"

services:
  pg-compeng:
    container_name: canada-demo-pg-compeng
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres

  control-api:
    container_name: canada-demo-control-api
    image: ghcr.io/dmi-feo/dloveryt_control_api:20240220-2
    environment:
      BI_API_UWSGI_WORKERS_COUNT: 4
      CONNECTOR_AVAILABILITY_VISIBLE: "clickhouse,postgres,chyt"
      RQE_FORCE_OFF: 1
      DL_CRY_ACTUAL_KEY_ID: key_1
      DL_CRY_KEY_VAL_ID_key_1: "h1ZpilcYLYRdWp7Nk8X1M1kBPiUi8rdjz9oBfHyUKIk="
      RQE_SECRET_KEY: ""
      US_HOST: "http://canada:8888"
      US_MASTER_TOKEN: "fake-us-master-token"
      CONFIG_PATH: "/etc/backend-configs/api.yaml"
    ports:
      - 8081:8080
    depends_on:
      - pg-compeng
    volumes:
      - ./backend-configs:/etc/backend-configs

  data-api:
    container_name: canada-demo-data-api
    image: ghcr.io/dmi-feo/dloveryt_data_api:20240220-2
    environment:
      GUNICORN_WORKERS_COUNT: 5
      RQE_FORCE_OFF: 1
      CACHES_ON: 0
      MUTATIONS_CACHES_ON: 0
      RQE_SECRET_KEY: ""
      DL_CRY_ACTUAL_KEY_ID: key_1
      DL_CRY_KEY_VAL_ID_key_1: "h1ZpilcYLYRdWp7Nk8X1M1kBPiUi8rdjz9oBfHyUKIk="
      BI_COMPENG_PG_ON: 1
      BI_COMPENG_PG_URL: "postgresql://postgres:postgres@pg-compeng:5432/postgres"
      US_HOST: "http://canada:8888"
      US_MASTER_TOKEN: "fake-us-master-token"
      CONFIG_PATH: "/etc/backend-configs/api.yaml"
    ports:
      - 8082:8080
    depends_on:
      - canada
      - pg-compeng
    volumes:
      - ./backend-configs:/etc/backend-configs

  datalens-ui:
    container_name: canada-demo-ui
    image: ghcr.io/dmi-feo/dloveryt_ui:20240305-1
    ports:
      - 8080:8080
    depends_on:
      - canada
      - control-api
      - data-api
    environment:
      APP_MODE: "full"
      APP_ENV: "production"
      APP_INSTALLATION: "opensource"
      AUTH_POLICY: "disabled"
      US_ENDPOINT: "http://canada:8888"
      BI_API_ENDPOINT: "http://control-api:8080"
      BI_DATA_ENDPOINT: "http://data-api:8080"
      NODE_EXTRA_CA_CERTS: "/usr/local/share/ca-certificates/cert.pem"
      HC: ${HC:-0}

  canada:
    container_name: canada
    image: ghcr.io/dmi-feo/canada:0.7.0
    ports:
      - 8888:8888
    environment:
      YT_HOST: ${YT_HOST}
      ROOT_COLLECTION_NODE_ID: ${ROOT_COLLECTION_NODE_ID}
      YT_AUTH_MODE: ${YT_AUTH_MODE:-disabled}
      CA_FILE: /etc/ssl/certs/ca-certificates.crt
    volumes:
      - ./canada-cert:/etc/ssl/certs
