docker_images:
  dl_control_api: ghcr.io/dmi-feo/dloveryt_control_api:20240220-2
  dl_data_api: ghcr.io/dmi-feo/dloveryt_data_api:20240220-2
  dl_ui: ghcr.io/dmi-feo/dloveryt_ui:20240226-2
  canada: ghcr.io/dmi-feo/canada:20240226-3

num_pods:
  dl_control_api: 1
  dl_data_api: 1
  dl_ui: 1
  canada: 1

yt_settings:
  auth_mode: disabled
  host: null
  root_collection_node_id: null

dl_ui_settings:
  use_highcharts: false

dl_control_api_settings:
  uwsgi_worker_num: 4

dl_data_api_settings:
  gunicorn_worker_num: 4

canada_settings:
  cert:
    use_custom_cert: false
    config_map_name: null
    config_map_key: null

ingress:
  host: localhost
  nginx_ingress_class: nginx
  tls:
    enabled: false
    secret_name: null

