docker_images:
  dl_control_api: ghcr.io/dmi-feo/dloveryt_control_api:20240218-2
  dl_data_api: ghcr.io/dmi-feo/dloveryt_data_api:20240218-2
  dl_ui: ghcr.io/dmi-feo/dloveryt_ui:20240219-1
  canada: ghcr.io/dmi-feo/canada:20240218-1

num_pods:
  dl_control_api: 1
  dl_data_api: 1
  dl_ui: 1
  canada: 1

yt_settings:
  auth_mode: disabled
  host: null
  root_collection_node_id: null

dl_ui_settings:
  use_highcharts: false

dl_control_api_settings:
  uwsgi_worker_num: 4

dl_data_api_settings:
  gunicorn_worker_num: 4

ingress:
  host: localhost

