{{- define "service_template" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service_name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .app_selector }}
  ports:
    - targetPort: {{ .port }}
      port: 80
{{ end }}