apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalens-ui
  labels:
    app: datalens-ui
spec:
  replicas: {{ .Values.num_pods.dl_ui }}
  selector:
    matchLabels:
      app: datalens-ui
  template:
    metadata:
      labels:
        app: datalens-ui
    spec:
      containers:
        - name: datalens-ui
          image: {{ .Values.docker_images.dl_ui }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_MODE
              value: "full"
            - name: APP_ENV
              value: "production"
            - name: APP_ENV
              value: "production"
            - name: APP_INSTALLATION
              value: "opensource"
            - name: AUTH_POLICY
              value: "disabled"  # it seems it is not used anywhere
            - name: US_ENDPOINT
              value: "http://canada"
            - name: BI_API_ENDPOINT
              value: "http://control-api"
            - name: BI_DATA_ENDPOINT
              value: "http://data-api"
            - name: NODE_EXTRA_CA_CERTS
              value: "/usr/local/share/ca-certificates/cert.pem"
            - name: HC
              value: {{ .Values.dl_ui_settings.use_highcharts | int | quote }}
            - name: CHYT_DEFAULT_CONN_ID
              value: {{ .Values.chyt_integration_settings.connection_id }}
            - name: CHYT_TEMP_DATASET_WORKBOOK_ID
              value: {{ .Values.chyt_integration_settings.temp_dataset_workbook_id }}
          # uncomment when readiness handler is ready
          readinessProbe:
            httpGet:
              port: 8080
              scheme: HTTP
              path: "/ping"
            initialDelaySeconds: 5
            periodSeconds: 10
